/**
 * Tools - Defines and implements all available tools that can be used by agents
 */

import { tool, generateObject, type LanguageModel, type ToolSet } from "ai";
import { z } from "zod";
import { fetchLyrics } from "~/lib/lyrics-api";
import { fetchVerseData } from "~/lib/quran-api";

/**
 * Tool Configuration
 */
export interface ToolConfig {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
}

// Schema definitions for tool inputs and outputs
export const VerseReferenceInputSchema = z.object({
  verseReference: z.string().describe("The verse reference in format chapter:verse"),
});

export const VerseReferenceOutputSchema = z.object({
  verse_key: z.string(),
  arabic_text: z.string(),
  chapter_name: z.string().optional(),
  translations: z
    .array(
      z.object({
        text: z.string(),
        translator: z.string().optional(),
      })
    )
    .optional(),
  error: z.string().optional(),
});

export const LyricsInputSchema = z.object({
  songTitle: z.string().describe("The title of the song"),
  artist: z.string().optional().describe("The artist name (optional)"),
});

export const LyricsToolOutputSchema = z.object({
  title: z.string(),
  artist: z.string(),
  lyrics: z.string(),
  url: z.string().optional(),
  thumbnail: z.string().optional(),
  error: z.string().optional(),
});

// Schema for comprehensive song analysis tool
export const ComprehensiveSongAnalysisInputSchema = z.object({
  songTitle: z.string().describe("The title of the song"),
  artist: z.string().optional().describe("The artist name (optional)"),
  lyrics: z.string().optional().describe("The song lyrics if already available"),
  userContext: z.string().optional().describe("The user's original query to detect language preference"),
});

export const ComprehensiveSongAnalysisOutputSchema = z.object({
  songInfo: z.object({
    title: z.string(),
    artist: z.string(),
    lyrics: z.string(),
    thumbnail: z.string().optional(),
  }),
  literaryAnalysis: z.object({
    structure: z.string().describe("Analysis of lyrical structure and flow"),
    tone: z.string().describe("Overall tone and emotional quality"),
    keyLines: z.array(z.object({
      line: z.string(),
      meaning: z.string(),
      significance: z.string(),
    })).describe("Most meaningful lines with analysis"),
    literaryDevices: z.array(z.string()).describe("Key literary devices found"),
  }),
  spiritualThemes: z.object({
    mainThemes: z.array(z.object({
      theme: z.string(),
      description: z.string(),
      universalLesson: z.string(),
    })),
    metaphors: z.array(z.object({
      metaphor: z.string(),
      spiritualMeaning: z.string(),
    })),
    emotionalJourney: z.string().describe("The emotional/spiritual journey of the song"),
  }),
  quranicConnections: z.array(z.object({
    theme: z.string(),
    verseReference: z.string(),
    verseText: z.string(),
    connection: z.string(),
    practicalWisdom: z.string(),
  })),
  practicalApplications: z.object({
    dailyReflections: z.array(z.string()),
    spiritualPractices: z.array(z.object({
      practice: z.string(),
      howTo: z.string(),
    })),
    reflectiveQuestions: z.array(z.string()),
    personalGrowthInsight: z.string(),
  }),
  overallMessage: z.string().describe("The unified spiritual message connecting song and Quranic wisdom"),
  // Dynamic UI labels generated by AI
  uiLabels: z.object({
    overviewTitle: z.string().describe("Title for the song overview section"),
    themesTitle: z.string().describe("Title for the spiritual themes section"),
    quranicTitle: z.string().describe("Title for the Quranic wisdom section"),
    practicalTitle: z.string().describe("Title for the practical applications section"),
    personalGrowthLabel: z.string().describe("Label for personal growth insight"),
    dailyReflectionsLabel: z.string().describe("Label for daily reflections"),
    reflectiveQuestionsLabel: z.string().describe("Label for reflective questions"),
  }),
});

/**
 * Tool Registry - All available tools
 */
export const TOOL_REGISTRY: Record<string, ToolConfig> = {
  // Verse reference tool - available to all agents
  verseReference: {
    id: "verseReference",
    name: "Verse Reference",
    description:
      "Reference a specific verse from the Quran by its chapter and verse number",
    enabled: true,
  },
  
  // Fetch lyrics tool - used by the Song Wisdom agent
  fetchLyrics: {
    id: "fetchLyrics",
    name: "Fetch Lyrics",
    description: "Fetch lyrics for a song by title and optionally artist",
    enabled: true,
  },

  // Comprehensive song analysis tool - the main tool for Song Wisdom agent
  comprehensiveSongAnalysis: {
    id: "comprehensiveSongAnalysis",
    name: "Comprehensive Song Analysis",
    description: "Performs complete spiritual and literary analysis of a song in one step",
    enabled: true,
  },
};

/**
 * Get a tool by ID
 */
export function getToolById(id: string): ToolConfig | undefined {
  return TOOL_REGISTRY[id];
}

/**
 * Get multiple tools by their IDs
 */
export function getToolsByIds(ids: string[]): ToolConfig[] {
  return ids
    .map(id => TOOL_REGISTRY[id])
    .filter(tool => tool !== undefined) as ToolConfig[];
}

/**
 * Get all available tools
 */
export function getAllTools(): ToolConfig[] {
  return Object.values(TOOL_REGISTRY);
}

/**
 * Get tool implementations for a specific set of tool IDs
 * 
 * @param toolIds Array of tool IDs that the agent can use
 * @param llm Language model instance for AI-powered tool operations
 * @returns A set of tool implementations
 */
export function getToolImplementations(toolIds: string[], llm: LanguageModel): ToolSet {
  const allTools = getAllToolImplementations(llm);
  
  // Filter tools based on provided tool IDs
  const filteredTools: ToolSet = {};
  
  for (const id of toolIds) {
    if (id in allTools) {
      filteredTools[id] = allTools[id];
    }
  }
  
  return filteredTools;
}

/**
 * Get all tool implementations
 * 
 * @param llm Language model instance for AI-powered tool operations
 * @returns A set of all tool implementations
 */
export function getAllToolImplementations(llm: LanguageModel): ToolSet {
  return {
    // Verse reference tool
    verseReference: tool({
      description: TOOL_REGISTRY.verseReference.description,
      parameters: VerseReferenceInputSchema,
      execute: async ({ verseReference }) => {
        try {
          // Fetch verse data directly using our utility function
          const verseData = await fetchVerseData(verseReference);

          if (verseData.error) {
            throw new Error(verseData.error);
          }

          return VerseReferenceOutputSchema.parse({
            verse_key: verseData.verse_key,
            arabic_text: verseData.arabic_text,
            chapter_name: verseData.chapter_name,
            translations: verseData.translations,
          });
        } catch (error) {
          console.error("Error fetching verse:", error);
          return VerseReferenceOutputSchema.parse({
            verse_key: verseReference,
            arabic_text: "",
            error:
              error instanceof Error
                ? error.message
                : "Failed to fetch verse data",
          });
        }
      },
    }),

    // Fetch lyrics tool
    fetchLyrics: tool({
      description: TOOL_REGISTRY.fetchLyrics.description,
      parameters: LyricsInputSchema,
      execute: async ({ songTitle, artist }) => {
        try {
          const lyricsData = await fetchLyrics(songTitle, artist);
          return LyricsToolOutputSchema.parse(lyricsData);
        } catch (error) {
          console.error("Error fetching lyrics:", error);
          return LyricsToolOutputSchema.parse({
            title: songTitle,
            artist: artist || "Unknown",
            lyrics: "",
            error:
              error instanceof Error
                ? error.message
                : "Failed to fetch lyrics",
          });
        }
      },
    }),

    // Comprehensive song analysis tool - combines everything into one powerful analysis
    comprehensiveSongAnalysis: tool({
      description: TOOL_REGISTRY.comprehensiveSongAnalysis.description,
      parameters: ComprehensiveSongAnalysisInputSchema,
      execute: async ({ songTitle, artist, lyrics, userContext }) => {
        try {
          let songLyrics = lyrics;
          let lyricsData = null;
          
          // Fetch lyrics if not provided
          if (!songLyrics) {
            try {
              lyricsData = await fetchLyrics(songTitle, artist);
              songLyrics = lyricsData.lyrics;
              if (!songLyrics) {
                throw new Error("Could not fetch lyrics for this song");
              }
            } catch (error) {
              throw new Error(`Unable to fetch lyrics: ${error instanceof Error ? error.message : 'Unknown error'}`);
            }
          }

          const prompt = `Analyze the song "${songTitle}" ${artist ? `by ${artist}` : ''} for spiritual insights and wisdom. 

${userContext ? `User context: "${userContext}"` : ''}

SONG LYRICS:
${songLyrics}

LANGUAGE INSTRUCTION: 
Respond in the same language that feels most natural based on the user's query and the song context. Pay attention to:
- What language did the user use when asking about this song?
- Is this an Indonesian song or from Indonesian context?
- What would feel most authentic and connecting for this specific user?

If the user communicated in Bahasa Indonesia (like "analisis lagu ini" or "apa makna lagu ini"), respond entirely in casual, warm Bahasa Indonesia. If the user used English, respond in English. Let the language flow naturally from the context.

Follow this structured approach for deeper analysis:

1. LITERARY ANALYSIS:
   - Overall structure and flow of the lyrics
   - Dominant tone and emotional quality  
   - Identify 3-5 most meaningful lines and provide deep analysis:
   - Validate user's feeling and emotions from the song

2. SPIRITUAL WISDOM EXTRACTION:
   From the key lines you identified, extract the core spiritual themes:
   - What fundamental life truths emerge from these lyrics? (Write as empowering revelations)
   - What spiritual struggles, hopes, or insights are being expressed? (Frame as transformative journey moments)
   - How do these themes relate to universal human spiritual journey? (Use "you" language that connects personally)
   - What metaphors reveal deeper spiritual meanings? (Explain with inspiring clarity)
   - Describe the emotional/spiritual transformation journey in the song (Tell it like a story of growth and discovery)

3. QURANIC CONNECTIONS (Deep Approach):
   Now, based on the spiritual wisdom you extracted above, find 3-5 Quranic verses that:
   - Directly address the same spiritual themes/struggles you identified
   - Offer guidance, comfort, or wisdom for those specific life situations
   - Complement or expand on the insights from the song
   
   For each connection:
   - Provide verse reference (chapter:verse) and translation
   - Explain HOW this verse specifically relates to the wisdom extracted from the song
   - Show what additional spiritual guidance the Quran provides beyond what the song offers
   - Connect it to practical life application

4. PRACTICAL APPLICATIONS:
   - 3-4 daily reflections inspired by the combined wisdom of song + Quran
   - 2-3 spiritual practices listeners can adopt
   - 3-4 deep reflective questions for personal growth
   - One key personal growth insight that synthesizes both sources

5. UNIFIED SPIRITUAL MESSAGE:
   - How do the song's wisdom and Quranic teachings create a complete spiritual framework?
   - What is the deeper life lesson when both are considered together?
   - How can this combined wisdom guide someone's spiritual journey?

6. UI LABELS:
   - Generate appropriate section titles and field labels in the same language as your analysis
   - Make them warm and engaging

IMPORTANT: Take time to really dig deep into the spiritual meaning of the lyrics before making Quranic connections. The connections should feel profound and meaningful, not superficial.

WRITING STYLE GUIDELINES:
- Use ACTIVE voice and inspiring language throughout
- Write as if you're speaking directly to someone going through this journey
- Instead of "This shows..." use "You discover..." or "Your heart learns..."
- Instead of "The lyrics express..." use "When you sing these words, you're actually declaring..."
- Make every insight feel like a personal revelation or empowerment
- Use story-telling language that paints vivid emotional pictures
- Focus on transformation, growth, and hope
- Write like you're a wise friend sharing life-changing insights

Be thoughtful, respectful of both artistic expression and Islamic teachings. Use a conversational, warm tone that matches the cultural context.`;

          const { object } = await generateObject({
            model: llm,
            prompt,
            schema: ComprehensiveSongAnalysisOutputSchema,
            temperature: 0.8,
          });

          // Ensure we include the song info
          object.songInfo = {
            title: songTitle,
            artist: artist || "Unknown Artist",
            lyrics: songLyrics,
            thumbnail: lyricsData?.thumbnail,
          };

          return object;
        } catch (error) {
          console.error("Error in comprehensive song analysis:", error);
          throw error;
        }
      },
    }),
  };
}
