"use client";

import * as React from "react";
import { cn } from "~/lib/utils";
import { Button } from "~/components/ui/button";
import {
  ChevronLeft,
  ChevronRight,
  Music,
  BookOpen,
  Heart,
  Lightbulb,
  Quote,
  Share2,
} from "lucide-react";
import { Logo } from "~/components/ui/logo";

interface SongAnalysisCardProps {
  state: string;
  args: any;
  result?: any;
}

interface SongAnalysisResult {
  songInfo: {
    title: string;
    artist: string;
    lyrics: string;
    thumbnail?: string;
  };
  literaryAnalysis: {
    structure: string;
    tone: string;
    keyLines: Array<{
      line: string;
      meaning: string;
      significance: string;
    }>;
    literaryDevices: string[];
  };
  spiritualThemes: {
    mainThemes: Array<{
      theme: string;
      description: string;
      universalLesson: string;
    }>;
    metaphors: Array<{
      metaphor: string;
      spiritualMeaning: string;
    }>;
    emotionalJourney: string;
  };
  quranicConnections: Array<{
    theme: string;
    verseReference: string;
    verseText: string;
    connection: string;
    practicalWisdom: string;
  }>;
  practicalApplications: {
    dailyReflections: string[];
    spiritualPractices: Array<{
      practice: string;
      howTo: string;
    }>;
    reflectiveQuestions: string[];
    personalGrowthInsight: string;
  };
  overallMessage: string;
  // Dynamic UI labels generated by AI
  uiLabels: {
    overviewTitle: string;
    themesTitle: string;
    quranicTitle: string;
    practicalTitle: string;
    personalGrowthLabel: string;
    dailyReflectionsLabel: string;
    reflectiveQuestionsLabel: string;
  };
}

export function SongAnalysisCard({
  state,
  args,
  result,
}: SongAnalysisCardProps) {
  const [activeSlide, setActiveSlide] = React.useState(0);

  // Loading state
  if (state === "partial-call" || state === "call") {
    return (
      <div className="w-full max-w-2xl mx-auto my-4">
        <div className="bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-950/30 dark:to-purple-950/30 rounded-2xl border border-blue-200/50 dark:border-blue-700/30 p-6">
          <div className="animate-pulse flex flex-col items-center text-center">
            <div className="h-16 w-16 rounded-full bg-blue-200 dark:bg-blue-800 flex items-center justify-center mb-4">
              <Music className="h-8 w-8 text-blue-600 dark:text-blue-400" />
            </div>
            <div className="h-6 w-48 bg-blue-200 dark:bg-blue-800 rounded-md mb-2"></div>
            <div className="h-4 w-32 bg-blue-100 dark:bg-blue-900 rounded-md mb-4"></div>
            <div className="space-y-3 w-full">
              <div className="h-4 bg-blue-100 dark:bg-blue-900 rounded w-3/4 mx-auto"></div>
              <div className="h-4 bg-blue-100 dark:bg-blue-900 rounded w-1/2 mx-auto"></div>
            </div>
            <p className="text-xs text-blue-600 dark:text-blue-400 mt-4">
              Finding the spiritual vibes in this song... ✨
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (result?.error) {
    return (
      <div className="w-full max-w-2xl mx-auto my-4">
        <div className="bg-red-50 dark:bg-red-950/30 rounded-2xl border border-red-200 dark:border-red-700/30 p-6">
          <div className="text-center">
            <div className="h-16 w-16 rounded-full bg-red-100 dark:bg-red-900 flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl">⚠️</span>
            </div>
            <h3 className="text-lg font-semibold text-red-800 dark:text-red-200 mb-2">
              Analysis Error
            </h3>
            <p className="text-red-600 dark:text-red-300 text-sm">
              {result.error}
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (!result) return null;

  const analysis: SongAnalysisResult = result;

  const slides = [
    {
      id: "overview",
      title: analysis.uiLabels.overviewTitle,
      icon: Music,
      color: "blue",
      content: (
        <div className="space-y-4">
          {/* Featured Quote from Song - Casual & Shareable */}
          {analysis.literaryAnalysis.keyLines &&
            analysis.literaryAnalysis.keyLines[0] && (
              <div className="bg-white dark:bg-black/40 rounded-xl p-6 border border-blue-200/30 dark:border-blue-700/30 mb-6">
                <div className="flex items-start gap-4">
                  {analysis.songInfo.thumbnail && (
                    <img
                      src={analysis.songInfo.thumbnail}
                      alt={`${analysis.songInfo.title} album cover`}
                      className="w-16 h-16 rounded-lg object-cover flex-shrink-0"
                    />
                  )}
                  <div className="flex-1">
                    <blockquote className="text-lg font-medium text-gray-900 dark:text-white leading-relaxed italic">
                      "{analysis.literaryAnalysis.keyLines[0].line}"
                    </blockquote>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">
                      {analysis.literaryAnalysis.keyLines[0].meaning}
                    </p>
                  </div>
                </div>
                <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-semibold text-gray-900 dark:text-white text-sm">
                        {analysis.songInfo.title}
                      </p>
                      <p className="text-blue-600 dark:text-blue-400 text-sm">
                        {analysis.songInfo.artist}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                      <Logo size="sm" />
                      SuperQuran
                    </div>
                  </div>
                </div>
              </div>
            )}

          {/* Additional Key Lines */}
          {analysis.literaryAnalysis.keyLines &&
            analysis.literaryAnalysis.keyLines.length > 1 && (
              <div className="space-y-3">
                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide">
                  More meaningful lines
                </p>
                {analysis.literaryAnalysis.keyLines
                  .slice(1, 4)
                  .map((keyLine, index) => (
                    <div
                      key={index}
                      className="bg-white/50 dark:bg-black/20 rounded-lg p-4 hover:bg-white/70 dark:hover:bg-black/30 transition-colors"
                    >
                      <div className="flex items-start gap-3">
                        <div className="text-lg">💫</div>
                        <div className="flex-1">
                          <blockquote className="text-sm font-medium text-gray-900 dark:text-white italic mb-1">
                            "{keyLine.line}"
                          </blockquote>
                          <p className="text-xs text-gray-600 dark:text-gray-300 mb-1">
                            {keyLine.meaning}
                          </p>
                          <p className="text-xs text-blue-600 dark:text-blue-400 font-medium">
                            ✨ {keyLine.significance}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
              </div>
            )}

          <div className="bg-blue-50/50 dark:bg-blue-950/20 rounded-lg p-4 border-l-4 border-blue-400">
            <p className="text-sm text-gray-700 dark:text-gray-300 italic">
              💫 {analysis.overallMessage}
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "themes",
      title: analysis.uiLabels.themesTitle,
      icon: Heart,
      color: "purple",
      content: (
        <div className="space-y-4">
          {/* Featured Spiritual Insight - Casual & Relatable */}
          {analysis.spiritualThemes.mainThemes[0] && (
            <div className="bg-white dark:bg-black/40 rounded-xl p-6 border border-purple-200/30 dark:border-purple-700/30 mb-6">
              <div className="text-center">
                <div className="text-3xl mb-3">💜</div>
                <blockquote className="text-lg font-medium text-gray-900 dark:text-white leading-relaxed">
                  {analysis.spiritualThemes.mainThemes[0].universalLesson}
                </blockquote>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">
                  {analysis.spiritualThemes.mainThemes[0].description}
                </p>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-semibold text-purple-800 dark:text-purple-200 text-sm">
                      {analysis.spiritualThemes.mainThemes[0].theme}
                    </p>
                    <p className="text-purple-600 dark:text-purple-400 text-sm">
                      from "{analysis.songInfo.title}"
                    </p>
                  </div>
                  <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                    <Logo size="sm" />
                    SuperQuran
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="bg-purple-50/50 dark:bg-purple-950/20 rounded-lg p-4 border-l-4 border-purple-400">
            <p className="text-sm text-purple-700 dark:text-purple-300 italic">
              🎵 {analysis.spiritualThemes.emotionalJourney}
            </p>
          </div>

          <div className="space-y-3">
            <p className="text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide">
              More spiritual vibes
            </p>
            {analysis.spiritualThemes.mainThemes
              .slice(1, 3)
              .map((theme, index) => (
                <div
                  key={index}
                  className="bg-white/50 dark:bg-black/20 rounded-lg p-4 hover:bg-white/70 dark:hover:bg-black/30 transition-colors"
                >
                  <div className="flex items-start gap-3">
                    <div className="text-lg">✨</div>
                    <div>
                      <h4 className="font-semibold text-purple-800 dark:text-purple-200 text-sm mb-1">
                        {theme.theme}
                      </h4>
                      <p className="text-xs text-gray-600 dark:text-gray-300 mb-2">
                        {theme.description}
                      </p>
                      <p className="text-xs text-purple-600 dark:text-purple-400 font-medium">
                        💡 {theme.universalLesson}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
          </div>
        </div>
      ),
    },
    {
      id: "quran",
      title: analysis.uiLabels.quranicTitle,
      icon: BookOpen,
      color: "green",
      content: (
        <div className="space-y-4">
          {/* Featured Quranic Verse - Casual & Meaningful */}
          {analysis.quranicConnections[0] && (
            <div className="bg-white dark:bg-black/40 rounded-xl p-6 border border-green-200/30 dark:border-green-700/30 mb-6">
              <div className="text-center">
                <div className="text-3xl mb-3">📖</div>
                <blockquote className="text-lg font-medium text-gray-900 dark:text-white leading-relaxed">
                  "{analysis.quranicConnections[0].verseText}"
                </blockquote>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">
                  {analysis.quranicConnections[0].connection}
                </p>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-semibold text-green-800 dark:text-green-200 text-sm">
                      Quran {analysis.quranicConnections[0].verseReference}
                    </p>
                    <p className="text-green-600 dark:text-green-400 text-sm">
                      vibes with "{analysis.songInfo.title}"
                    </p>
                  </div>
                  <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                    <Logo size="sm" />
                    SuperQuran
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="bg-green-50/50 dark:bg-green-950/20 rounded-lg p-4 border-l-4 border-green-400">
            <p className="text-sm text-green-700 dark:text-green-300 italic">
              🌿{" "}
              {analysis.quranicConnections[0]?.practicalWisdom ||
                "Finding connections between music and faith"}
            </p>
          </div>

          {analysis.quranicConnections.length > 1 && (
            <div className="space-y-3">
              <p className="text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide">
                More Quranic connections
              </p>
              {analysis.quranicConnections
                .slice(1, 2)
                .map((connection, index) => (
                  <div
                    key={index}
                    className="bg-white/50 dark:bg-black/20 rounded-lg p-4 hover:bg-white/70 dark:hover:bg-black/30 transition-colors"
                  >
                    <div className="flex items-start gap-3">
                      <div className="text-lg">🕌</div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <span className="text-xs bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 px-2 py-1 rounded">
                            {connection.verseReference}
                          </span>
                          <span className="text-sm font-medium text-green-800 dark:text-green-200">
                            {connection.theme}
                          </span>
                        </div>
                        <p className="text-sm text-gray-700 dark:text-gray-300 italic mb-2">
                          "{connection.verseText}"
                        </p>
                        <p className="text-xs text-gray-600 dark:text-gray-400 mb-1">
                          {connection.connection}
                        </p>
                        <p className="text-xs text-green-600 dark:text-green-400 font-medium">
                          💡 {connection.practicalWisdom}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
            </div>
          )}
        </div>
      ),
    },
    {
      id: "practice",
      title: analysis.uiLabels.practicalTitle,
      icon: Lightbulb,
      color: "amber",
      content: (
        <div className="space-y-4">
          {/* Featured Personal Growth Insight - Casual & Actionable */}
          <div className="bg-white dark:bg-black/40 rounded-xl p-6 border border-amber-200/30 dark:border-amber-700/30 mb-6">
            <div className="text-center">
              <div className="text-3xl mb-3">🌟</div>
              <blockquote className="text-lg font-medium text-gray-900 dark:text-white leading-relaxed">
                {analysis.practicalApplications.personalGrowthInsight}
              </blockquote>
            </div>
            <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-semibold text-amber-800 dark:text-amber-200 text-sm">
                    Your growth journey
                  </p>
                  <p className="text-amber-600 dark:text-amber-400 text-sm">
                    inspired by "{analysis.songInfo.title}"
                  </p>
                </div>
                <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                  <Logo size="sm" />
                  SuperQuran
                </div>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4">
            <div className="bg-amber-50/50 dark:bg-amber-950/20 rounded-lg p-4 border-l-4 border-amber-400">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-lg">☀️</span>
                <h4 className="font-semibold text-amber-800 dark:text-amber-200 text-sm">
                  {analysis.uiLabels.dailyReflectionsLabel}
                </h4>
              </div>
              <div className="space-y-2">
                {analysis.practicalApplications.dailyReflections
                  .slice(0, 3)
                  .map((reflection, index) => (
                    <div
                      key={index}
                      className="text-sm text-gray-700 dark:text-gray-300 bg-white/50 dark:bg-black/20 p-3 rounded-lg"
                    >
                      <span className="font-medium text-amber-600 dark:text-amber-400">
                        {index + 1}.
                      </span>{" "}
                      {reflection}
                    </div>
                  ))}
              </div>
            </div>

            <div className="bg-amber-50/50 dark:bg-amber-950/20 rounded-lg p-4 border-l-4 border-amber-400">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-lg">🤔</span>
                <h4 className="font-semibold text-amber-800 dark:text-amber-200 text-sm">
                  {analysis.uiLabels.reflectiveQuestionsLabel}
                </h4>
              </div>
              <div className="space-y-2">
                {analysis.practicalApplications.reflectiveQuestions
                  .slice(0, 2)
                  .map((question, index) => (
                    <div
                      key={index}
                      className="text-sm text-gray-700 dark:text-gray-300 bg-white/50 dark:bg-black/20 p-3 rounded-lg"
                    >
                      <span className="font-medium text-amber-600 dark:text-amber-400">
                        Q:
                      </span>{" "}
                      {question}
                    </div>
                  ))}
              </div>
            </div>
          </div>
        </div>
      ),
    },
  ];

  const currentSlide = slides[activeSlide];
  const colorMap = {
    blue: "from-blue-50 to-blue-100 dark:from-blue-950/30 dark:to-blue-900/20 border-blue-200 dark:border-blue-700/30",
    purple:
      "from-purple-50 to-purple-100 dark:from-purple-950/30 dark:to-purple-900/20 border-purple-200 dark:border-purple-700/30",
    green:
      "from-green-50 to-green-100 dark:from-green-950/30 dark:to-green-900/20 border-green-200 dark:border-green-700/30",
    amber:
      "from-amber-50 to-amber-100 dark:from-amber-950/30 dark:to-amber-900/20 border-amber-200 dark:border-amber-700/30",
  };

  // Handle sharing functionality
  const handleShare = async () => {
    if (!result) return;

    const analysis: SongAnalysisResult = result;
    const currentSlideData = slides[activeSlide];

    // Get current slide's featured quote
    let shareText = "";
    let shareTitle = "";

    switch (currentSlideData.id) {
      case "overview":
        if (analysis.literaryAnalysis.keyLines?.[0]) {
          shareText = `"${analysis.literaryAnalysis.keyLines[0].line}" - ${analysis.songInfo.title} by ${analysis.songInfo.artist}`;
          shareTitle = "This song hit different 🎵";
        }
        break;
      case "themes":
        if (analysis.spiritualThemes.mainThemes?.[0]) {
          shareText = `"${analysis.spiritualThemes.mainThemes[0].universalLesson}" - spiritual vibes from ${analysis.songInfo.title}`;
          shareTitle = "Found some deep meaning ✨";
        }
        break;
      case "quran":
        if (analysis.quranicConnections?.[0]) {
          shareText = `"${analysis.quranicConnections[0].verseText}" - Quran ${analysis.quranicConnections[0].verseReference}, connects beautifully with ${analysis.songInfo.title}`;
          shareTitle = "Music meets faith 📖";
        }
        break;
      case "practice":
        shareText = `"${analysis.practicalApplications.personalGrowthInsight}" - growth insight from ${analysis.songInfo.title}`;
        shareTitle = "Personal growth vibes 🌟";
        break;
    }

    if (navigator.share && shareText) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: window.location.href,
        });
      } catch (error) {
        // Fallback to copying to clipboard
        await navigator.clipboard.writeText(
          `${shareText}\n\n${shareTitle} - ${window.location.href}`
        );
      }
    } else if (shareText) {
      // Fallback to copying to clipboard
      await navigator.clipboard.writeText(
        `${shareText}\n\n${shareTitle} - ${window.location.href}`
      );
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto my-4">
      <div
        className={cn(
          "bg-gradient-to-br rounded-2xl border p-6 transition-all duration-500",
          colorMap[currentSlide.color as keyof typeof colorMap]
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div
              className={cn(
                "w-10 h-10 rounded-full flex items-center justify-center",
                currentSlide.color === "blue" && "bg-blue-200 dark:bg-blue-800",
                currentSlide.color === "purple" &&
                  "bg-purple-200 dark:bg-purple-800",
                currentSlide.color === "green" &&
                  "bg-green-200 dark:bg-green-800",
                currentSlide.color === "amber" &&
                  "bg-amber-200 dark:bg-amber-800"
              )}
            >
              <currentSlide.icon
                className={cn(
                  "w-5 h-5",
                  currentSlide.color === "blue" &&
                    "text-blue-600 dark:text-blue-300",
                  currentSlide.color === "purple" &&
                    "text-purple-600 dark:text-purple-300",
                  currentSlide.color === "green" &&
                    "text-green-600 dark:text-green-300",
                  currentSlide.color === "amber" &&
                    "text-amber-600 dark:text-amber-300"
                )}
              />
            </div>
            <h2 className="font-semibold text-gray-900 dark:text-white">
              {currentSlide.title}
            </h2>
          </div>

          {/* Navigation */}
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={handleShare}
              className="h-8 w-8 p-0"
              title="Share this wisdom"
            >
              <Share2 className="h-4 w-4" />
            </Button>
            <div className="w-px h-4 bg-gray-300 dark:bg-gray-600 mx-1"></div>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setActiveSlide(Math.max(0, activeSlide - 1))}
              disabled={activeSlide === 0}
              className="h-8 w-8 p-0"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="text-xs text-gray-500 dark:text-gray-400 min-w-[3rem] text-center">
              {activeSlide + 1} / {slides.length}
            </span>
            <Button
              variant="ghost"
              size="sm"
              onClick={() =>
                setActiveSlide(Math.min(slides.length - 1, activeSlide + 1))
              }
              disabled={activeSlide === slides.length - 1}
              className="h-8 w-8 p-0"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Content */}
        <div className="min-h-[200px]">{currentSlide.content}</div>

        {/* Dots indicator */}
        <div className="flex justify-center gap-2 mt-6">
          {slides.map((_, index) => (
            <button
              key={index}
              onClick={() => setActiveSlide(index)}
              className={cn(
                "w-2 h-2 rounded-full transition-all",
                index === activeSlide
                  ? "bg-gray-600 dark:bg-gray-300 w-6"
                  : "bg-gray-300 dark:bg-gray-600"
              )}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
